version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-space
    hostname: sqlserver-wsl
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "TestPassword123#"
      MSSQL_PID: Developer
      MSSQL_AGENT_ENABLED: true
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver/data:/var/opt/mssql/data
      - ./sqlserver/log:/var/opt/mssql/log
      - ./sqlserver/secrets:/var/opt/mssql/secrets

  rabbitmq:
    container_name: rabbitmq-space
    image: rabbitmq:3.7.14-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    container_name: mongodb-space
    image: mongo:latest
    ports:
      - "27017:27017"